{
  "uid" : "371ab4c6b6ddad12",
  "name" : "nonReentrant function can be called",
  "fullName" : "Contract: ReentrancyGuard.nonReentrant function can be called",
  "historyId" : "e59896602ed4a139da28e26adc8442c",
  "time" : {
    "start" : 1635554848366,
    "stop" : 1635554849335,
    "duration" : 969
  },
  "description" : "",
  "descriptionHtml" : "",
  "status" : "broken",
  "statusMessage" : "Returned error: HTTPConnectionPool(host='solana', port=8899): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f23a183c9d0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))",
  "statusTrace" : "Error: Returned error: HTTPConnectionPool(host='solana', port=8899): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f23a183c9d0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))\n                    at Context.<anonymous> (test/security/ReentrancyGuard.test.js:10:51)\n                    at processImmediate (node:internal/timers:464:21)",
  "flaky" : false,
  "newFailed" : false,
  "beforeStages" : [ ],
  "afterStages" : [ ],
  "labels" : [ {
    "name" : "suite",
    "value" : "Contract: ReentrancyGuard"
  }, {
    "name" : "testClass",
    "value" : "Contract: ReentrancyGuard"
  }, {
    "name" : "testMethod",
    "value" : "nonReentrant function can be called"
  }, {
    "name" : "package",
    "value" : "Contract: ReentrancyGuard"
  }, {
    "name" : "resultFormat",
    "value" : "allure1"
  } ],
  "parameters" : [ ],
  "links" : [ ],
  "hidden" : true,
  "retry" : true,
  "extra" : {
    "categories" : [ ],
    "tags" : [ ]
  },
  "source" : "371ab4c6b6ddad12.json",
  "parameterValues" : [ ]
}