{
  "uid" : "21f4222afc5349f5",
  "name" : "recognize trusted forwarder",
  "fullName" : "Contract: ERC2771Context.recognize trusted forwarder",
  "historyId" : "c3956d54d6afe498dbd01c6aa8753891",
  "time" : {
    "start" : 1635782692896,
    "stop" : 1635782693853,
    "duration" : 957
  },
  "description" : "",
  "descriptionHtml" : "",
  "status" : "broken",
  "statusMessage" : "Returned error: HTTPConnectionPool(host='solana', port=8899): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f238be8c2b0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))",
  "statusTrace" : "Error: Returned error: HTTPConnectionPool(host='solana', port=8899): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f238be8c2b0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))\n                    at Context.<anonymous> (test/metatx/ERC2771Context.test.js:19:48)\n                    at processImmediate (node:internal/timers:464:21)",
  "flaky" : false,
  "newFailed" : false,
  "beforeStages" : [ ],
  "afterStages" : [ ],
  "labels" : [ {
    "name" : "suite",
    "value" : "Contract: ERC2771Context"
  }, {
    "name" : "testClass",
    "value" : "Contract: ERC2771Context"
  }, {
    "name" : "testMethod",
    "value" : "recognize trusted forwarder"
  }, {
    "name" : "package",
    "value" : "Contract: ERC2771Context"
  }, {
    "name" : "resultFormat",
    "value" : "allure1"
  } ],
  "parameters" : [ ],
  "links" : [ ],
  "hidden" : false,
  "retry" : false,
  "extra" : {
    "severity" : "normal",
    "retries" : [ {
      "uid" : "917901f636b96fc8",
      "status" : "broken",
      "statusDetails" : "Returned error: HTTPConnectionPool(host='solana', port=8899): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f238be7b4c0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))",
      "time" : {
        "start" : 1635782589435,
        "stop" : 1635782589995,
        "duration" : 560
      }
    }, {
      "uid" : "53b7df6273b2cd73",
      "status" : "broken",
      "statusDetails" : "Returned error: HTTPConnectionPool(host='solana', port=8899): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f238be7b670>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))",
      "time" : {
        "start" : 1635782587786,
        "stop" : 1635782588360,
        "duration" : 574
      }
    }, {
      "uid" : "86c6fa03a431dd9c",
      "status" : "broken",
      "statusDetails" : "Returned error: HTTPConnectionPool(host='solana', port=8899): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f23a0435fa0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))",
      "time" : {
        "start" : 1635782587425,
        "stop" : 1635782587985,
        "duration" : 560
      }
    }, {
      "uid" : "ebcda031be96a80a",
      "status" : "broken",
      "statusDetails" : "Returned error: HTTPConnectionPool(host='solana', port=8899): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f23a17de490>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))",
      "time" : {
        "start" : 1635782546379,
        "stop" : 1635782548948,
        "duration" : 2569
      }
    }, {
      "uid" : "e66dfcf6c678e207",
      "status" : "broken",
      "statusDetails" : "Returned error: HTTPConnectionPool(host='solana', port=8899): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f23a04527c0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))",
      "time" : {
        "start" : 1635782533223,
        "stop" : 1635782534192,
        "duration" : 969
      }
    }, {
      "uid" : "8bc778dd7de41248",
      "status" : "broken",
      "statusDetails" : "Returned error: HTTPConnectionPool(host='solana', port=8899): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f23a07c31c0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))",
      "time" : {
        "start" : 1635782509037,
        "stop" : 1635782509603,
        "duration" : 566
      }
    }, {
      "uid" : "f2a4f028ea8d2833",
      "status" : "broken",
      "statusDetails" : "Returned error: HTTPConnectionPool(host='solana', port=8899): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f238be9edc0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))",
      "time" : {
        "start" : 1635782497062,
        "stop" : 1635782497646,
        "duration" : 584
      }
    }, {
      "uid" : "d1f1c99e537231bb",
      "status" : "broken",
      "statusDetails" : "Returned error: HTTPConnectionPool(host='solana', port=8899): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f23a17aa430>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))",
      "time" : {
        "start" : 1635782494481,
        "stop" : 1635782495042,
        "duration" : 561
      }
    } ],
    "categories" : [ {
      "name" : "Test defects",
      "matchedStatuses" : [ ],
      "flaky" : false
    } ],
    "history" : {
      "statistic" : {
        "failed" : 0,
        "broken" : 4,
        "skipped" : 0,
        "passed" : 0,
        "unknown" : 0,
        "total" : 4
      },
      "items" : [ {
        "uid" : "5eb2729d12067274",
        "reportUrl" : "https://neonlabsorg.github.io/neon-compatibility/8//#testresult/5eb2729d12067274",
        "status" : "broken",
        "statusDetails" : "Returned error: Transaction simulation failed: Error processing Instruction 0: invalid account data for instruction",
        "time" : {
          "start" : 1635589894524,
          "stop" : 1635589905500,
          "duration" : 10976
        }
      }, {
        "uid" : "182d518278e5998c",
        "reportUrl" : "https://neonlabsorg.github.io/neon-compatibility/7//#testresult/182d518278e5998c",
        "status" : "broken",
        "statusDetails" : "Returned error: HTTPConnectionPool(host='solana', port=8899): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f23a28660d0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))",
        "time" : {
          "start" : 1635554968896,
          "stop" : 1635554969868,
          "duration" : 972
        }
      }, {
        "uid" : "eff8f597a3833341",
        "reportUrl" : "https://neonlabsorg.github.io/neon-compatibility/6//#testresult/eff8f597a3833341",
        "status" : "broken",
        "statusDetails" : "HH110: Invalid JSON-RPC response received: <html>\n                <head><title>502 Bad Gateway</title></head>\n                <body>\n                <center><h1>502 Bad Gateway</h1></center>\n                <hr><center>nginx/1.18.0 (Ubuntu)</center>\n                </body>\n                </html>\n                ",
        "time" : {
          "start" : 1635551252954,
          "stop" : 1635551253038,
          "duration" : 84
        }
      } ]
    },
    "tags" : [ ]
  },
  "source" : "21f4222afc5349f5.json",
  "parameterValues" : [ ]
}